load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
  name = "jazelle",
  url = "https://registry.yarnpkg.com/jazelle/-/jazelle-JAZELLE_VERSION.tgz",
  strip_prefix = "package",
)

load("@jazelle//:workspace-rules.bzl", "jazelle_dependencies")
jazelle_dependencies(
  node_version = "NODE_VERSION",
  node_sha256 = {
    "mac": "",
    "linux": "",
    "windows": "",
  },
  yarn_version = "YARN_VERSION",
  yarn_sha256 = "",
)
