packageExtensions:
  "@apollo/react-ssr@*":
    peerDependencies:
      apollo-client: "*"
  "@jest/core@*":
    peerDependencies:
      prettier: "*"
  "@jest/test-sequencer@*":
    peerDependencies:
      prettier: "*"
  baseui@*:
    dependencies:
      styletron-standard: "*"
  eslint-config-uber-universal-stage-3@*:
    peerDependencies:
      babel-eslint: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  jest-cli@*:
    peerDependencies:
      prettier: "*"
  jest-config@*:
    peerDependencies:
      prettier: "*"
  jest-jasmine2@*:
    peerDependencies:
      prettier: "*"
  jest-runner@*:
    peerDependencies:
      prettier: "*"
  jest-runtime@*:
    peerDependencies:
      prettier: "*"
  jest@*:
    peerDependencies:
      prettier: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
