#!/usr/bin/env bash
export DISPLAY=:99.0
/etc/init.d/xvfb start

./node_modules/.bin/nyc --instrument=false --exclude-after-remap=false --reporter=json ./node_modules/.bin/unitest --browser=dist-tests/browser.js
./node_modules/.bin/codecov -f coverage/coverage-final.json
