#!/usr/bin/env bash
./node_modules/.bin/nyc --instrument=false --exclude-after-remap=false --reporter=text --reporter=json node test/index.js || exit 1
bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json -n node
