// flow-typed signature: 9354ca6dba6e2be49497486e6e246f1a
// flow-typed version: <<STUB>>/eventsource_v*/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eventsource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eventsource' {
  declare module.exports: any;
}
