// flow-typed signature: 55dd50f412afef8339edfbf25141411b
// flow-typed version: <<STUB>>/@wojtekmaj/enzyme-adapter-react-17_vlatest

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@wojtekmaj/enzyme-adapter-react-17'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@wojtekmaj/enzyme-adapter-react-17' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@wojtekmaj/enzyme-adapter-react-17/build/detectFiberTags' {
  declare module.exports: any;
}

declare module '@wojtekmaj/enzyme-adapter-react-17/build/findCurrentFiberUsingSlowPath' {
  declare module.exports: any;
}

declare module '@wojtekmaj/enzyme-adapter-react-17/build' {
  declare module.exports: any;
}

declare module '@wojtekmaj/enzyme-adapter-react-17/build/ReactSeventeenAdapter' {
  declare module.exports: any;
}

declare module '@wojtekmaj/enzyme-adapter-react-17/src/detectFiberTags' {
  declare module.exports: any;
}

declare module '@wojtekmaj/enzyme-adapter-react-17/src/findCurrentFiberUsingSlowPath' {
  declare module.exports: any;
}

declare module '@wojtekmaj/enzyme-adapter-react-17/src' {
  declare module.exports: any;
}

declare module '@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@wojtekmaj/enzyme-adapter-react-17/build/detectFiberTags.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/build/detectFiberTags'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/build/findCurrentFiberUsingSlowPath.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/build/findCurrentFiberUsingSlowPath'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/build/index' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/build'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/build/index.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/build'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/build/ReactSeventeenAdapter.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/build/ReactSeventeenAdapter'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/src/detectFiberTags.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/src/detectFiberTags'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/src/findCurrentFiberUsingSlowPath.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/src/findCurrentFiberUsingSlowPath'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/src/index' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/src'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/src/index.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/src'>;
}
declare module '@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js' {
  declare module.exports: $Exports<'@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter'>;
}
