steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-plugin-font-loader-react
        image-repository: 296822479253.dkr.ecr.us-east-2.amazonaws.com/fusionjs
  - wait
  - command: yarn flow
    name: ':flowtype:'
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-font-loader-react
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-font-loader-react
  - name: ':chrome: :white_check_mark:'
    command: .buildkite/browserTests
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-font-loader-react
  - name: ':node: :white_check_mark:'
    command: .buildkite/nodeTests
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-plugin-font-loader-react
